
purpose_id_map = {
    'Purpose-m1': 1,
    'Purpose-m2': 2,
    'Purpose-m3': 3,
    'Purpose-m4': 4,
    'Purpose-m5': 5,
    'Purpose-m6': 6,
    'Purpose-m7': 7,
    'Purpose-m8': 8,
    'Purpose-m9': 9,
    'Purpose-m10': 10,
    'Purpose-m11': 11,
    'Purpose-m12': 12,
    'Purpose-msm1': 13,
    'Purpose-msm2': 14,
    'Purpose-msm3': 15,
    'Purpose-msm4': 16,
    'Purpose-b1': 17,
    'Purpose-b2': 18,
    'Purpose-b3': 19,
    'Purpose-b4': 20,
    'Purpose-z1': 21,
    'Purpose-z2': 22,
    'Purpose-z3': 23,
    'Purpose-z4': 24,
    'Purpose-z5': 25,
    'Purpose-z6': 26,
    'Purpose-z7': 27,
    'Purpose-z8': 28
}


purposes_list = [
    "Qubate club",
    "Able club",
    "Kural club",
    "SOIL club",
    "Band Agartha",
    "Agam",
    "Books and beyond",
    "Studio KCT",
    "Evoke",
    "Varnam",
    "Varnam",
    "Tamil mandram",
    "Athletic Track",
    "Olipadi", "KVB Bank", "temple", "K mart", "ORB", "munch box at Admin block", "Auditorium", "Seminar hall", "Guest house", "Olipadi", "KVB Bank", "temple", "admin block", "gym", "football court",
    "badminton court", "Basketball court", "Volleyball court", "cricket ground", "CAD lab",
    "MAD lab", "Matlab", "Physics lab",
    "EEE lab",
    "Library", "Project room", "Computer lab", "EEE lab", "Bio tech lab", "Library", "Project room",
    "Computer lab",
    "IT lab", "Library", "Re",
    "B block",
    "C block",
    "D block",
    "E block",
    "girls hostel",
    "boys hostel",
    "admin block", "ks cafe",
    "munch box",
    "kore",
    "east kore",
    "cafe coffee day", "visit_campus",
    "explore"
]
